GET http://localhost:5000/feedback/


################################

POST http://localhost:5000/feedback/createfeedback/
Content-Type: application/json 

{
    "name":"Kavinbharathi",
    "mobile_Number" : 9384592506,
    "email_id" : "kavinbharathi@gmail.com",
    "feedback" : "Good as kB"
}